sonar.projectKey=fiap-software-architecture-tech_fast-food
sonar.organization=fiap-software-architecture-tech
sonar.sca.exclusions="**/*.test.ts,**/*-mock.ts"
sonar.coverage.exclusions="**/*.test.ts,**/*-mock.ts"
sonar.javascript.lcov.reportPaths=coverage/lcov.info
# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=fast-food
sonar.projectVersion=1.0

sonar.sources=.
