version: "3.8"
services:
  db:
    image: mysql:8
    container_name: fastfood_db
    environment:
      MYSQL_DATABASE: fastfood
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastfood_app
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql://admin:admin123@db:3306/fastfood
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  db_data:
