version: "3.8"
services:
  db:
    image: mysql:8
    container_name: fastfood_db
    environment:
      MYSQL_DATABASE: fastfood
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  api-dev:
    image: node:22-alpine
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    command: sh -c "npm ci && npm run start:dev"
    depends_on:
      - db

  api-prod:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db

volumes:
  db_data:
